dbdata:
  image: busybox
  volumes:
    - ./db_data:/var/lib/postgresql/data
  command: /bin/true

db:
  image: postgres:9.4
  volumes_from:
    - dbdata
  # ports:
  #   - "5432:5432"

app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
